-keep class com.vay.camerasnap.HookEntry { public <init>(); }
-keepnames class com.vay.camerasnap.SnapService
-keepnames class com.vay.camerasnap.SettingsActivity
-dontwarn io.github.libxposed.annotation.**
